### ISSUE TITLE
GitHub Flow steps for 8amlaser - San Francisco, CA

### ISSUE THREAD

**Issue by 8amlaser** [githubteacher/everyone-may-2016#127]
### San Francisco, CA

- [x] Create a branch

- [x] Add some comments

- [x] Open a pull request

- [ ] Have a convo about the open PR

- [ ] Additional commits based on open PR

- [x] Merge branch

**Comment by 8amlaser** [comment]
Still missing some steps...

**Comment by madepu81** [comment]
Let me look the changes.
